### ISSUE TITLE
Installing on PHP 7, you have to enter the database credentials twice

### ISSUE THREAD

**Issue by dsnopek** [d6lts/drupal#11] opened 2018-09-15 17:19 UTC
This is a very low priority bug, because most people aren't installing new Drupal 6 sites, but it's really annoying during testing!

On the step of install.php where it asks for the database credentials, you always have to enter the database credentials twice. The first time you submit the form, it just comes back blank with no messages. On the second submit, it works per normal.

I suspect that this issue has to do with the default value for some variable being the wrong type, because the automatic type conversion in PHP 7 is much stricter than PHP 5. I've noticed other situations where Drupal 6 code would set a variables default value to empty string and then use it as an array, and other such oddities that get automatically corrected in PHP 5, but fail to work in PHP 7. But that's just a random guess.

**Comment by hanoii** [comment] 2018-09-16 00:00
I saw this and gave it a try, I like these challenges :)

It's the oddest of things. It's not that you need to submit the form twice, just refreshing makes it work. It seems to be a timing issue. Adding a `sleep(3)` (and not less) towards the end of `drupal_rewrite_settings()` makes it work. The problem is the next refresh, being super fast, is not picking up the modified settings.php.

That function is not closing `$fp`, but even adding `fflush($fp)` and `fclose($fp)` didn't make it work, it only works with the sleep. I saw different questions online in a similar venue, like: https://www.digitalocean.com/community/questions/how-to-speed-up-php-s-write-to-file-time

But it doesn't make much sense.

Anyway, I might come back to this (or not) but wanted to share my findings!

**Comment by dsnopek** [comment] 2018-09-16 00:01
Wow, that's weird! Thanks for sharing :-)

Luckily, this is pretty low priority...

**Closed as completed** 2018-09-16 02:07 UTC
