### ISSUE TITLE
drupal 6 modified for php7.2 not recognised by drush 8

### ISSUE THREAD

**Issue by cptX** [d6lts/drupal#15] opened 2018-09-25 11:59 UTC
Hi, I have an issue which I cannot solve:
I have modified my drupal 6 installation to make it compatible to php7.2 and the site is actually working ok and is up and running.
The only problem I found is that drush 8 cannot recognise the site and actually cannot connect to it's database. Did you have a similar problem?
I have posted this question also here (https://github.com/drush-ops/drush/issues/3700) but as people don't consider drupal 6 working with php 7+ I don't expect to find any answer there... 
Any hint would be useful...

**Comment by dsnopek** [comment] 2018-09-25 13:48
Actually, I'm seeing the same problem. I'm not sure how I didn't notice this previously! Drush seems not to bootstrap Drupal

**Comment by cptX** [comment] 2018-09-25 14:46
I'm going to follow this way https://github.com/drush-ops/drush/pull/2002 and report back...

**Comment by dsnopek** [comment] 2018-09-25 14:53
Ok, great, thanks! Let me know how it goes.

I started experimenting with running the Drush test suite, but haven't gotten far. I haven't tried the changes on that issue yet.

**Comment by cptX** [comment] 2018-09-25 15:21
#2002 (comment) worked for me!!!!

**Comment by dsnopek** [comment] 2018-09-29 14:31
We're using this slightly more conservative one, which will hopefully get merged into Drush:

https://github.com/drush-ops/drush/pull/3706

**Comment by DrupaListo-com** [comment] 2018-10-26 08:31
Short howto do the fix for fellow googlers:

Here's a direct link to that last one 3706 :
https://patch-diff.githubusercontent.com/raw/drush-ops/drush/pull/3706.diff

1. download it somewhere via:
$ wget -O /tmp/drush-fix-D6.patch "https://patch-diff.githubusercontent.com/raw/drush-ops/drush/pull/3706.diff"

2. and if you have drush 8 installed in say /some/dir , go find the file includes/sitealias.inc in there.
Faster to just use systemwide `locate includes/sitealias.inc`.

Go into same dir as drush's include/ dir.

run:
`patch -p1 < /tmp/drush-fix-D6.patch`

Go test if drush now works in your D6 site. Mine worked like a charm.

**Comment by yaazkal** [comment] 2018-11-21 02:51
Hi, even after aplying the patch to drush I'm still getting

`Checking DB credentials yielded error: Unable to find a matching SQL Class. Drush cannot find your database connection details.`

Trying to run D6.46 on php 7.0 using BOA (drush alias file, nginx file, settings file seems correct to me).

Any hint will be useful, thanks.

**Comment by yaazkal** [comment] 2018-11-21 02:54
Oh, I must clarify that the platform verifyes correctly, but that error is for the site verify task. I'm running `drush @hostmaster hosting-task @example.com verify --debug` in order to see the message I talked before because Aegir UI just shows `Drush command terminated abnormally due to an unrecoverable error.` which of course is not pretty informative.

**Comment by dsnopek** [comment] 2018-11-21 14:26
That error sounds like the patch didn't add the `Sqlmysqli.php` file it should have added, but got the other change (because it's looking for the mysqli file rather than the mysql one). Can you check that that file got created correctly?

**Comment by yaazkal** [comment] 2018-11-21 14:33
Actually I manually edited/created those files based on the patch. So I can confirm the file is there.

**Comment by dsnopek** [comment] 2018-11-21 14:41
Hm. Sorry, no other ideas then, that's all that I can think of from that error message.

**Comment by yaazkal** [comment] 2018-11-21 16:27
It's ok, thanks so much. I'll work on this later, so if I have any update/solution I'll update this issue.

**Comment by hansfn** [comment] 2019-12-21 09:40
I suggest closing this issue as it was fixed in Drush 8.1.18 (or something) and the current version of Drush (8) is 8.3.2.

**Comment by dsnopek** [comment] 2019-12-23 15:16
Yep, this was fixed originally in Drush 8.1.18. Closing!

**Closed as completed by dsnopek** 2019-12-23 15:16 UTC
